# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ash_pb2 as ash__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ash_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HealthStub(object):
    """ash-code IPC contract between the Rust host process and the Python
    sidecar (ashpy). Finalized in M1.

    Services:
    Health           — liveness + version handshake (smoke test)
    LlmProvider      — model/provider abstraction (impl lands in M2)
    SkillRegistry    — SKILL.md discovery + invocation (impl lands in M5)
    CommandRegistry  — slash command registry (impl lands in M6)
    Harness          — query-loop hooks / middleware control plane (impl M3)
    ToolRegistry     — third-party tool plugins (impl M3+)

    Conventions:
    * All bytes fields are UTF-8 JSON unless noted.
    * All string fields are UTF-8.
    * RPCs returning `stream` are server-streaming.
    * Unimplemented RPCs must return gRPC status UNIMPLEMENTED with a
    human-readable message naming the owning milestone.

    ========================================================================
    Health — smoke test and version handshake
    ========================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/ash.v1.Health/Ping',
                request_serializer=ash__pb2.PingRequest.SerializeToString,
                response_deserializer=ash__pb2.PingResponse.FromString,
                _registered_method=True)


class HealthServicer(object):
    """ash-code IPC contract between the Rust host process and the Python
    sidecar (ashpy). Finalized in M1.

    Services:
    Health           — liveness + version handshake (smoke test)
    LlmProvider      — model/provider abstraction (impl lands in M2)
    SkillRegistry    — SKILL.md discovery + invocation (impl lands in M5)
    CommandRegistry  — slash command registry (impl lands in M6)
    Harness          — query-loop hooks / middleware control plane (impl M3)
    ToolRegistry     — third-party tool plugins (impl M3+)

    Conventions:
    * All bytes fields are UTF-8 JSON unless noted.
    * All string fields are UTF-8.
    * RPCs returning `stream` are server-streaming.
    * Unimplemented RPCs must return gRPC status UNIMPLEMENTED with a
    human-readable message naming the owning milestone.

    ========================================================================
    Health — smoke test and version handshake
    ========================================================================
    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=ash__pb2.PingRequest.FromString,
                    response_serializer=ash__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ash.v1.Health', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ash.v1.Health', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Health(object):
    """ash-code IPC contract between the Rust host process and the Python
    sidecar (ashpy). Finalized in M1.

    Services:
    Health           — liveness + version handshake (smoke test)
    LlmProvider      — model/provider abstraction (impl lands in M2)
    SkillRegistry    — SKILL.md discovery + invocation (impl lands in M5)
    CommandRegistry  — slash command registry (impl lands in M6)
    Harness          — query-loop hooks / middleware control plane (impl M3)
    ToolRegistry     — third-party tool plugins (impl M3+)

    Conventions:
    * All bytes fields are UTF-8 JSON unless noted.
    * All string fields are UTF-8.
    * RPCs returning `stream` are server-streaming.
    * Unimplemented RPCs must return gRPC status UNIMPLEMENTED with a
    human-readable message naming the owning milestone.

    ========================================================================
    Health — smoke test and version handshake
    ========================================================================
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.Health/Ping',
            ash__pb2.PingRequest.SerializeToString,
            ash__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LlmProviderStub(object):
    """========================================================================
    LlmProvider — implemented in M2
    ========================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProviders = channel.unary_unary(
                '/ash.v1.LlmProvider/ListProviders',
                request_serializer=ash__pb2.ListProvidersRequest.SerializeToString,
                response_deserializer=ash__pb2.ListProvidersResponse.FromString,
                _registered_method=True)
        self.Capabilities = channel.unary_unary(
                '/ash.v1.LlmProvider/Capabilities',
                request_serializer=ash__pb2.CapabilitiesRequest.SerializeToString,
                response_deserializer=ash__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.unary_stream(
                '/ash.v1.LlmProvider/ChatStream',
                request_serializer=ash__pb2.ChatRequest.SerializeToString,
                response_deserializer=ash__pb2.ChatDelta.FromString,
                _registered_method=True)
        self.Switch = channel.unary_unary(
                '/ash.v1.LlmProvider/Switch',
                request_serializer=ash__pb2.SwitchRequest.SerializeToString,
                response_deserializer=ash__pb2.SwitchResponse.FromString,
                _registered_method=True)


class LlmProviderServicer(object):
    """========================================================================
    LlmProvider — implemented in M2
    ========================================================================
    """

    def ListProviders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Capabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Switch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviders,
                    request_deserializer=ash__pb2.ListProvidersRequest.FromString,
                    response_serializer=ash__pb2.ListProvidersResponse.SerializeToString,
            ),
            'Capabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.Capabilities,
                    request_deserializer=ash__pb2.CapabilitiesRequest.FromString,
                    response_serializer=ash__pb2.CapabilitiesResponse.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=ash__pb2.ChatRequest.FromString,
                    response_serializer=ash__pb2.ChatDelta.SerializeToString,
            ),
            'Switch': grpc.unary_unary_rpc_method_handler(
                    servicer.Switch,
                    request_deserializer=ash__pb2.SwitchRequest.FromString,
                    response_serializer=ash__pb2.SwitchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ash.v1.LlmProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ash.v1.LlmProvider', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LlmProvider(object):
    """========================================================================
    LlmProvider — implemented in M2
    ========================================================================
    """

    @staticmethod
    def ListProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.LlmProvider/ListProviders',
            ash__pb2.ListProvidersRequest.SerializeToString,
            ash__pb2.ListProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Capabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.LlmProvider/Capabilities',
            ash__pb2.CapabilitiesRequest.SerializeToString,
            ash__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ash.v1.LlmProvider/ChatStream',
            ash__pb2.ChatRequest.SerializeToString,
            ash__pb2.ChatDelta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Switch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.LlmProvider/Switch',
            ash__pb2.SwitchRequest.SerializeToString,
            ash__pb2.SwitchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SkillRegistryStub(object):
    """========================================================================
    SkillRegistry — implemented in M5
    ========================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/ash.v1.SkillRegistry/List',
                request_serializer=ash__pb2.ListSkillsRequest.SerializeToString,
                response_deserializer=ash__pb2.ListSkillsResponse.FromString,
                _registered_method=True)
        self.Invoke = channel.unary_unary(
                '/ash.v1.SkillRegistry/Invoke',
                request_serializer=ash__pb2.InvokeSkillRequest.SerializeToString,
                response_deserializer=ash__pb2.InvokeSkillResponse.FromString,
                _registered_method=True)
        self.Reload = channel.unary_unary(
                '/ash.v1.SkillRegistry/Reload',
                request_serializer=ash__pb2.ReloadRequest.SerializeToString,
                response_deserializer=ash__pb2.ReloadResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/ash.v1.SkillRegistry/Watch',
                request_serializer=ash__pb2.WatchRequest.SerializeToString,
                response_deserializer=ash__pb2.SkillEvent.FromString,
                _registered_method=True)


class SkillRegistryServicer(object):
    """========================================================================
    SkillRegistry — implemented in M5
    ========================================================================
    """

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SkillRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=ash__pb2.ListSkillsRequest.FromString,
                    response_serializer=ash__pb2.ListSkillsResponse.SerializeToString,
            ),
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=ash__pb2.InvokeSkillRequest.FromString,
                    response_serializer=ash__pb2.InvokeSkillResponse.SerializeToString,
            ),
            'Reload': grpc.unary_unary_rpc_method_handler(
                    servicer.Reload,
                    request_deserializer=ash__pb2.ReloadRequest.FromString,
                    response_serializer=ash__pb2.ReloadResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=ash__pb2.WatchRequest.FromString,
                    response_serializer=ash__pb2.SkillEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ash.v1.SkillRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ash.v1.SkillRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SkillRegistry(object):
    """========================================================================
    SkillRegistry — implemented in M5
    ========================================================================
    """

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.SkillRegistry/List',
            ash__pb2.ListSkillsRequest.SerializeToString,
            ash__pb2.ListSkillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.SkillRegistry/Invoke',
            ash__pb2.InvokeSkillRequest.SerializeToString,
            ash__pb2.InvokeSkillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.SkillRegistry/Reload',
            ash__pb2.ReloadRequest.SerializeToString,
            ash__pb2.ReloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ash.v1.SkillRegistry/Watch',
            ash__pb2.WatchRequest.SerializeToString,
            ash__pb2.SkillEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CommandRegistryStub(object):
    """========================================================================
    CommandRegistry — implemented in M6
    ========================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/ash.v1.CommandRegistry/List',
                request_serializer=ash__pb2.ListCommandsRequest.SerializeToString,
                response_deserializer=ash__pb2.ListCommandsResponse.FromString,
                _registered_method=True)
        self.Run = channel.unary_unary(
                '/ash.v1.CommandRegistry/Run',
                request_serializer=ash__pb2.RunCommandRequest.SerializeToString,
                response_deserializer=ash__pb2.RunCommandResponse.FromString,
                _registered_method=True)
        self.Reload = channel.unary_unary(
                '/ash.v1.CommandRegistry/Reload',
                request_serializer=ash__pb2.ReloadRequest.SerializeToString,
                response_deserializer=ash__pb2.ReloadResponse.FromString,
                _registered_method=True)


class CommandRegistryServicer(object):
    """========================================================================
    CommandRegistry — implemented in M6
    ========================================================================
    """

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=ash__pb2.ListCommandsRequest.FromString,
                    response_serializer=ash__pb2.ListCommandsResponse.SerializeToString,
            ),
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=ash__pb2.RunCommandRequest.FromString,
                    response_serializer=ash__pb2.RunCommandResponse.SerializeToString,
            ),
            'Reload': grpc.unary_unary_rpc_method_handler(
                    servicer.Reload,
                    request_deserializer=ash__pb2.ReloadRequest.FromString,
                    response_serializer=ash__pb2.ReloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ash.v1.CommandRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ash.v1.CommandRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommandRegistry(object):
    """========================================================================
    CommandRegistry — implemented in M6
    ========================================================================
    """

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.CommandRegistry/List',
            ash__pb2.ListCommandsRequest.SerializeToString,
            ash__pb2.ListCommandsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.CommandRegistry/Run',
            ash__pb2.RunCommandRequest.SerializeToString,
            ash__pb2.RunCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.CommandRegistry/Reload',
            ash__pb2.ReloadRequest.SerializeToString,
            ash__pb2.ReloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HarnessStub(object):
    """========================================================================
    Harness — query-loop hooks / middleware control plane (impl M3)
    ========================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnTurnStart = channel.unary_unary(
                '/ash.v1.Harness/OnTurnStart',
                request_serializer=ash__pb2.TurnContext.SerializeToString,
                response_deserializer=ash__pb2.HookDecision.FromString,
                _registered_method=True)
        self.OnToolCall = channel.unary_unary(
                '/ash.v1.Harness/OnToolCall',
                request_serializer=ash__pb2.ToolCallEvent.SerializeToString,
                response_deserializer=ash__pb2.HookDecision.FromString,
                _registered_method=True)
        self.OnStreamDelta = channel.unary_unary(
                '/ash.v1.Harness/OnStreamDelta',
                request_serializer=ash__pb2.DeltaEvent.SerializeToString,
                response_deserializer=ash__pb2.Empty.FromString,
                _registered_method=True)
        self.OnTurnEnd = channel.unary_unary(
                '/ash.v1.Harness/OnTurnEnd',
                request_serializer=ash__pb2.TurnResult.SerializeToString,
                response_deserializer=ash__pb2.Empty.FromString,
                _registered_method=True)


class HarnessServicer(object):
    """========================================================================
    Harness — query-loop hooks / middleware control plane (impl M3)
    ========================================================================
    """

    def OnTurnStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnToolCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnStreamDelta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnTurnEnd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HarnessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnTurnStart': grpc.unary_unary_rpc_method_handler(
                    servicer.OnTurnStart,
                    request_deserializer=ash__pb2.TurnContext.FromString,
                    response_serializer=ash__pb2.HookDecision.SerializeToString,
            ),
            'OnToolCall': grpc.unary_unary_rpc_method_handler(
                    servicer.OnToolCall,
                    request_deserializer=ash__pb2.ToolCallEvent.FromString,
                    response_serializer=ash__pb2.HookDecision.SerializeToString,
            ),
            'OnStreamDelta': grpc.unary_unary_rpc_method_handler(
                    servicer.OnStreamDelta,
                    request_deserializer=ash__pb2.DeltaEvent.FromString,
                    response_serializer=ash__pb2.Empty.SerializeToString,
            ),
            'OnTurnEnd': grpc.unary_unary_rpc_method_handler(
                    servicer.OnTurnEnd,
                    request_deserializer=ash__pb2.TurnResult.FromString,
                    response_serializer=ash__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ash.v1.Harness', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ash.v1.Harness', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Harness(object):
    """========================================================================
    Harness — query-loop hooks / middleware control plane (impl M3)
    ========================================================================
    """

    @staticmethod
    def OnTurnStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.Harness/OnTurnStart',
            ash__pb2.TurnContext.SerializeToString,
            ash__pb2.HookDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnToolCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.Harness/OnToolCall',
            ash__pb2.ToolCallEvent.SerializeToString,
            ash__pb2.HookDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnStreamDelta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.Harness/OnStreamDelta',
            ash__pb2.DeltaEvent.SerializeToString,
            ash__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnTurnEnd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.Harness/OnTurnEnd',
            ash__pb2.TurnResult.SerializeToString,
            ash__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ToolRegistryStub(object):
    """========================================================================
    ToolRegistry — third-party tool plugins (impl M3+)
    ========================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/ash.v1.ToolRegistry/List',
                request_serializer=ash__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=ash__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.Invoke = channel.unary_unary(
                '/ash.v1.ToolRegistry/Invoke',
                request_serializer=ash__pb2.InvokeToolRequest.SerializeToString,
                response_deserializer=ash__pb2.InvokeToolResponse.FromString,
                _registered_method=True)


class ToolRegistryServicer(object):
    """========================================================================
    ToolRegistry — third-party tool plugins (impl M3+)
    ========================================================================
    """

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=ash__pb2.ListToolsRequest.FromString,
                    response_serializer=ash__pb2.ListToolsResponse.SerializeToString,
            ),
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=ash__pb2.InvokeToolRequest.FromString,
                    response_serializer=ash__pb2.InvokeToolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ash.v1.ToolRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ash.v1.ToolRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolRegistry(object):
    """========================================================================
    ToolRegistry — third-party tool plugins (impl M3+)
    ========================================================================
    """

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.ToolRegistry/List',
            ash__pb2.ListToolsRequest.SerializeToString,
            ash__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.ToolRegistry/Invoke',
            ash__pb2.InvokeToolRequest.SerializeToString,
            ash__pb2.InvokeToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class QueryHostStub(object):
    """========================================================================
    QueryHost — Rust-hosted turn engine, called FROM the Python FastAPI
    layer (reverse gRPC direction). Added in M4.
    ========================================================================

    Runs on 127.0.0.1:50052 inside the ash-code container. Only the
    `ashpy` FastAPI process is expected to call it; it is never exposed
    outside the container.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunTurn = channel.unary_stream(
                '/ash.v1.QueryHost/RunTurn',
                request_serializer=ash__pb2.RunTurnRequest.SerializeToString,
                response_deserializer=ash__pb2.TurnDelta.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/ash.v1.QueryHost/ListSessions',
                request_serializer=ash__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=ash__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/ash.v1.QueryHost/GetSession',
                request_serializer=ash__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=ash__pb2.GetSessionResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/ash.v1.QueryHost/DeleteSession',
                request_serializer=ash__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=ash__pb2.DeleteSessionResponse.FromString,
                _registered_method=True)


class QueryHostServicer(object):
    """========================================================================
    QueryHost — Rust-hosted turn engine, called FROM the Python FastAPI
    layer (reverse gRPC direction). Added in M4.
    ========================================================================

    Runs on 127.0.0.1:50052 inside the ash-code container. Only the
    `ashpy` FastAPI process is expected to call it; it is never exposed
    outside the container.
    """

    def RunTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryHostServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunTurn': grpc.unary_stream_rpc_method_handler(
                    servicer.RunTurn,
                    request_deserializer=ash__pb2.RunTurnRequest.FromString,
                    response_serializer=ash__pb2.TurnDelta.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=ash__pb2.ListSessionsRequest.FromString,
                    response_serializer=ash__pb2.ListSessionsResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=ash__pb2.GetSessionRequest.FromString,
                    response_serializer=ash__pb2.GetSessionResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=ash__pb2.DeleteSessionRequest.FromString,
                    response_serializer=ash__pb2.DeleteSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ash.v1.QueryHost', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ash.v1.QueryHost', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryHost(object):
    """========================================================================
    QueryHost — Rust-hosted turn engine, called FROM the Python FastAPI
    layer (reverse gRPC direction). Added in M4.
    ========================================================================

    Runs on 127.0.0.1:50052 inside the ash-code container. Only the
    `ashpy` FastAPI process is expected to call it; it is never exposed
    outside the container.
    """

    @staticmethod
    def RunTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ash.v1.QueryHost/RunTurn',
            ash__pb2.RunTurnRequest.SerializeToString,
            ash__pb2.TurnDelta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.QueryHost/ListSessions',
            ash__pb2.ListSessionsRequest.SerializeToString,
            ash__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.QueryHost/GetSession',
            ash__pb2.GetSessionRequest.SerializeToString,
            ash__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ash.v1.QueryHost/DeleteSession',
            ash__pb2.DeleteSessionRequest.SerializeToString,
            ash__pb2.DeleteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
